### ISSUE TITLE
Successive calls to BeanBuilder.aRandomInstanceOf() creates same instance sometimes

### ISSUE THREAD

**Issue by abuabdul** [eXparity/exparity-stub#9] opened 2016-03-16 21:05 UTC
One in 1000 times, successive calls to BeanBuilder.aRandomInstanceOf() creates two same instances which broke one of my tests. Is there any way we can make sure it creates random instance with all the properties having different values from other instances.

**Comment by stewbis** [comment] 2016-03-17 07:19
Hi, the bean builder was intended to create random values not exclusive values because trying to guarantee exclusivity would be impossible in some cases. For instance, if large numbers of short random strings are requested, or if random beans are created in different JVMs, or different sessions.

That said, it would make sense to try to make it exclusive as possible for instance by ensuring that random strings produced in the same JVM are different if possible.

Is it possible for you to attach the bean class you were randomly populated so I can see the types of fields, or ideally create a unit test which shows the problem and issue a pull request for me to merge it in.

Thanks

Stewart

**Comment by abuabdul** [comment] 2016-03-17 10:16
I used exclusivity to populate different instances always, hence the problem should be fixed. Just in case, you want to use unit test to fix the problem for pull request, the class is familiar to you if you remember from your old work. This bean is named RefDataRef, that has generic type of another bean named Market which has only a string property along with Guid property.

**Comment by stewbis** [comment] 2016-03-19 16:50
Hi,

If I remember RefDataRef contains both a String and a Guid but equality of RefDataRef is based only the Guid which is a byte array and the String isn't relevant. Please supply a unit test to repeatedly produce the problem and I can see what changes would be required. I don't want to guess at the point when it's fixed therefore you providing the unit test gives the scope of functionality to work within.

If you can't provide the fix then a solution is for you to provide a custom factory to create your Guid objects via the method:

RefDataRef randomRef = RandomBuilder.aRandomInstanceOf(RefDataRef.class,
    RandomBuilder.factory(() -> Guid.createGuid())
    );

**Comment by abuabdul** [comment] 2016-03-20 20:03
The problem occurred when the unit test called BeanBuilder.aRandomInstanceOf() twice to create two instances of RefDataRef successively. The subsequent part of the unit test expected to work with two different RefDataRef objects. Instead of creating the different instances, the BeanBuilder.aRandomInstanceOf() created two same RefDataRef instances, hence the unit test failed. I fixed the issue by making sure the property is set different value that is expected by the unit test to pass. Please see the fix below.

BeanBuilder.aRandomInstanceOf(RefDataRef.class, property("label","abc"))
BeanBuilder.aRandomInstanceOf(RefDataRef.class, property("label","xyz"))

I could not reproduce this repeatedly. However, I am gonna fork this exparity-stub.and work on it to see if I can reproduce it.

**Comment by stewbis** [comment] 2018-10-08 14:48
Closing issue due to lack of unit test example

**Closed by stewbis** 2018-10-08 14:48 UTC
